KAFKA-8360: Docs do not mention RequestQueueSize JMX metric
apache/kafka-site pull request #220
Opened 2019-07-13 10:39 UTC by ankit-kumar-25

What? :: Mentioning "Request Queue Size" under [Monitoring](https://kafka.apache.org/documentation/#monitoring) tab. RequestQueueSize is an important metric to monitor the number of requests in the queue. As a crowded queue might face issue processing incoming or outgoing requests

Can you please review this?

Thanks!!

2019-11-22 07:54 UTC, xinzhuxiansheng commented
I didn't find it on the official website for a long time, but "Kafka. Network: type = requestchannel, name = requestqueuesize" MBean is using jconsole to view the broker.

2020-09-21 13:58 UTC, viktorsomogyi requested changes
Please make a PR against the ops.html found in the Kafka project:
https://github.com/apache/kafka/blob/trunk/docs/ops.html

This doc in the asf-site is. generated on release and I think we don't need to update them now.

2020-09-21 13:58 UTC, viktorsomogyi commented
Otherwise it looks good, I can approve it once you create the PR in the kafka repo.

2020-09-21 15:27 UTC, ankit-kumar-25 commented
Hey @viktorsomogyi, 

Thank you for the pointers, I have created a PR against the ops.html available in the Kafka project: https://github.com/apache/kafka/pull/9314

2020-09-23 11:23 UTC, closed without merging